import { apiRequest, apiUpload, kioskApiUpload } from './apiClient';
export interface EnrollmentResult { success: boolean; employee_id: string; face_profile_id?: string; enrollment_status: string; message: string; face_detected: boolean; face_count: number; }
export interface LivenessChallengeResponse { challenge_type: string; instruction: string; session_id: string; }
export interface LivenessResult { passed: boolean; challenge_type: string; liveness_score: number; failure_reason: string | null; frame_count: number; processing_time_ms: number; session_id: string; }
export async function enrollFace(id: string, blob: Blob, consentId: string, di: Record<string,unknown>): Promise<EnrollmentResult> { const fd = new FormData(); fd.append('employee_id', id); fd.append('image', blob, 'e.jpg'); fd.append('consent_id', consentId); fd.append('device_info', JSON.stringify(di)); return apiUpload<EnrollmentResult>('/api/face/enroll', fd); }
export async function requestLivenessChallenge(): Promise<LivenessChallengeResponse> { return apiRequest<LivenessChallengeResponse>('/api/liveness/challenge', { method: 'POST', body: JSON.stringify({}) }); }
export async function submitLivenessCheck(sid: string, ct: string, frames: Blob[], di: Record<string,unknown>): Promise<LivenessResult> { const fd = new FormData(); fd.append('session_id', sid); fd.append('challenge_type', ct); frames.forEach((f, i) => fd.append('frames', f, `f_${i}.jpg`)); fd.append('device_info', JSON.stringify(di)); return apiUpload<LivenessResult>('/api/liveness/check', fd); }
export async function requestKioskLivenessChallenge(): Promise<LivenessChallengeResponse> { return kioskApiUpload<LivenessChallengeResponse>('/api/kiosk/liveness/challenge', new FormData()); }
export async function submitKioskLivenessCheck(sid: string, ct: string, frames: Blob[], di: Record<string,unknown>): Promise<LivenessResult> { const fd = new FormData(); fd.append('session_id', sid); fd.append('challenge_type', ct); frames.forEach((f, i) => fd.append('frames', f, `f_${i}.jpg`)); fd.append('device_info', JSON.stringify(di)); return kioskApiUpload<LivenessResult>('/api/kiosk/liveness/check', fd); }
