import { useEffect, useState } from 'react';
import { Loader2, Save, CheckCircle2, KeyRound, Copy } from 'lucide-react';
import { supabase } from '@/services/supabaseClient';
import { useAuth } from '@/hooks/useAuth';
import { getKioskKeyStatus, rotateKioskKey } from '@/services/attendanceService';
import { PageHeader } from '@/components/AppShell';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
interface AppSettings { id?: string; late_threshold_minutes: number; work_start_time: string; work_end_time: string; require_liveness: boolean; require_check_out: boolean; allow_multiple_check_in: boolean; duplicate_check_window_minutes: number; face_match_threshold: number; liveness_threshold: number; max_allowed_faces: number; min_face_confidence: number; geofencing_enabled: boolean; }
const DEFAULTS: AppSettings = { late_threshold_minutes: 15, work_start_time: '09:00', work_end_time: '17:00', require_liveness: true, require_check_out: false, allow_multiple_check_in: false, duplicate_check_window_minutes: 60, face_match_threshold: 0.68, liveness_threshold: 0.7, max_allowed_faces: 1, min_face_confidence: 0.7, geofencing_enabled: false };
export function Settings() {
  const { user } = useAuth();
  const [settings, setSettings] = useState<AppSettings | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  const [kioskConfigured, setKioskConfigured] = useState(false); const [kioskRotatedAt, setKioskRotatedAt] = useState<string | null>(null); const [kioskNewKey, setKioskNewKey] = useState<string | null>(null); const [kioskRotating, setKioskRotating] = useState(false); const [kioskError, setKioskError] = useState<string | null>(null);
  useEffect(() => { (async () => { try { const s = await getKioskKeyStatus(); setKioskConfigured(s.configured); setKioskRotatedAt(s.rotated_at); } catch { /* */ } })(); }, []);
  const handleRotateKiosk = async () => { setKioskRotating(true); setKioskError(null); setKioskNewKey(null); try { const res = await rotateKioskKey(); setKioskNewKey(res.kiosk_api_key); setKioskConfigured(true); setKioskRotatedAt(new Date().toISOString()); } catch (err) { setKioskError(err instanceof Error ? err.message : 'Could not generate a kiosk key'); } finally { setKioskRotating(false); } };
  useEffect(() => { (async () => { if (!user?.organizationId) { setSettings({ ...DEFAULTS }); setLoading(false); return; } const { data } = await supabase.from('app_settings').select('*').eq('organization_id', user.organizationId).maybeSingle(); setSettings(data ? (data as AppSettings) : { ...DEFAULTS }); setLoading(false); })(); }, [user]);
  const handleSave = async () => { if (!settings || !user?.organizationId) return; setSaving(true); setSaved(false); try { await supabase.from('app_settings').upsert({ organization_id: user.organizationId, ...settings }, { onConflict: 'organization_id' }); setSaved(true); setTimeout(() => setSaved(false), 3000); } finally { setSaving(false); } };
  if (loading) return <div className="flex items-center justify-center py-12"><Loader2 className="w-6 h-6 text-primary animate-spin" /></div>;
  if (!settings) return <Card className="p-12 text-center text-muted-foreground">No settings available.</Card>;
  const num = (label: string, key: keyof AppSettings, step = '1') => (<div className="space-y-1.5"><Label>{label}</Label><Input type="number" step={step} value={settings[key] as number} onChange={(e) => setSettings({ ...settings, [key]: +e.target.value })} /></div>);
  return (<div className="max-w-3xl"><PageHeader title="Settings" description="Configure attendance rules and verification thresholds" /><div className="space-y-6">
    <Card><CardHeader><CardTitle>Attendance Rules</CardTitle></CardHeader><CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">{num('Late Threshold (minutes)', 'late_threshold_minutes')}{num('Duplicate Window (minutes)', 'duplicate_check_window_minutes')}<div className="space-y-1.5"><Label>Work Start Time</Label><Input type="time" value={settings.work_start_time} onChange={(e) => setSettings({ ...settings, work_start_time: e.target.value })} /></div><div className="space-y-1.5"><Label>Work End Time</Label><Input type="time" value={settings.work_end_time} onChange={(e) => setSettings({ ...settings, work_end_time: e.target.value })} /></div></CardContent></Card>
    <Card><CardHeader><CardTitle>Verification Thresholds</CardTitle></CardHeader><CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">{num('Face Match Threshold', 'face_match_threshold', '0.01')}{num('Liveness Threshold', 'liveness_threshold', '0.05')}{num('Min Face Confidence', 'min_face_confidence', '0.05')}{num('Max Allowed Faces', 'max_allowed_faces')}<p className="text-xs text-muted-foreground md:col-span-2">Tip: InsightFace works best around 0.66–0.72; dlib/face_recognition around 0.60.</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Feature Toggles</CardTitle></CardHeader><CardContent className="space-y-3">{([['require_liveness','Require liveness detection'],['require_check_out','Require check-out'],['allow_multiple_check_in','Allow multiple check-ins per day'],['geofencing_enabled','Enable geofencing']] as const).map(([key, label]) => (<label key={key} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={settings[key] as boolean} onChange={(e) => setSettings({ ...settings, [key]: e.target.checked })} className="w-4 h-4 rounded border-input accent-[var(--primary)]" />{label}</label>))}</CardContent></Card>
    <Card><CardHeader><CardTitle>Kiosk (no-login attendance screen)</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Generate a kiosk key and enter it once on the device you'll use for walk-up check-in/out at the home screen. Anyone at that device can mark attendance by scanning their face. Rotating disconnects any device paired with the old key.</p><div className="flex items-center gap-2 text-sm"><KeyRound className="w-4 h-4 text-primary" />{kioskConfigured ? <span>Kiosk key configured{kioskRotatedAt ? ` · rotated ${new Date(kioskRotatedAt).toLocaleString()}` : ''}</span> : <span className="text-muted-foreground">No kiosk key generated yet</span>}</div>{kioskNewKey && (<div className="space-y-1.5"><Label>New kiosk key (shown once — copy it now)</Label><div className="flex gap-2"><Input readOnly value={kioskNewKey} className="font-mono text-xs" /><Button type="button" variant="secondary" size="icon" onClick={() => navigator.clipboard.writeText(kioskNewKey)}><Copy className="w-4 h-4" /></Button></div></div>)}{kioskError && <p className="text-sm text-destructive">{kioskError}</p>}<Button variant={kioskConfigured ? 'outline' : 'default'} onClick={handleRotateKiosk} disabled={kioskRotating}>{kioskRotating ? <Loader2 className="w-4 h-4 animate-spin" /> : <KeyRound className="w-4 h-4" />}{kioskConfigured ? 'Rotate Kiosk Key' : 'Generate Kiosk Key'}</Button></CardContent></Card>
    <div className="flex items-center gap-3"><Button onClick={handleSave} disabled={saving}>{saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}Save Settings</Button>{saved && <span className="flex items-center gap-1 text-sm text-success"><CheckCircle2 className="w-4 h-4" />Saved</span>}</div>
  </div></div>);
}
